name: Publish using ko
on: 
  push
jobs:
  build_and_publish:
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: '1.23.x'
      - uses: actions/checkout@v3

      - uses: ko-build/setup-ko@v0.6
      - run: KO_DEFAULTBASEIMAGE=homeassistant/armv7-base-debian ko build --platform=linux/arm/v7 ./cmd/podfetch
