name: Publish using ko

on: 
  push

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: '1.24.x'
      - uses: actions/checkout@v3

      - uses: ko-build/setup-ko@v0.6
      - run: ko build






      - uses: actions/
      
      - name: Build and push the image
        run : |
          docker login --username jabersmith --password ${{ secrets.WF_PAT }} ghcr.io
          docker build . --tag ghcr.io/jabersmith/podfetch:latest
          docker push ghcr.io/jabersmith/podfetch:latest
